#
# Custom head includes - should be a YAML List, e.g.:
#

head_includes:
 - <meta id="extViewportMeta" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
 - "<style> html, body {margin: 0; padding: 0; overflow: hidden} </style>"

#
# Custom body includes - should be a YAML List, e.g.:
#

body_includes:
 - "  <script>"
 - "    document.body.addEventListener('touchmove', function(event) {"
 - "      console.log(event.source);"
 - "      //if (event.source == document.body)"
 - "        event.preventDefault();"
 - "    }, false);"
 - "  </script>"
 - "<div id='stars'></div>"
 - "<div id='stars2'></div>"
 - "<div id='stars3'></div>"
 - "<div id='moon'>"
 - "  <div class='craterCon'>"
 - "    <div class='craters'></div>"
 - "  </div>"
 - "  <div class='glow'></div>"
 - "</div>"
#
# Styles
#

white: "#ffffff"
red: "#ce3e33"
pink: "#e91e63"
purple: "#9c27b0"
deep_purple: "#673ab7"
indigo: "#385396"
blue: "#2196f3"
light_blue: "#52aaec"
cyan: "#00bcd4"
teal: "#009688"
green: "#4caf50"
light_green: "#8bc34a"
lime: "#cddc39"
yellow: "#f8bc2e"
amber: "#ffc107"
orange: "#ff9800"
deep_orange: "#ff5722"
brown: "#795548"
grey: "#757575"
light_grey: "#eeeeee"
blue_grey: "#607d8b"

light_yellow: "#fff176"

white0_background: "background-color: rgba(255, 255, 255, 0.05)"
white_background: "background-color: rgba(255, 255, 255, 0.85)"
red_background: "background-color: rgba(206, 62, 51, 0.85)"
pink_background: "background-color: rgba(233, 30, 99, 0.85)"
purple_background: "background-color: rgba(156, 39, 176, 0.85)"
deep_purple_background: "background-color: rgba(103, 58, 183, 0.85)"
indigo_background: "background-color: rgba(56, 83, 150, 0.85)"
blue_background: "background-color: rgba(33, 150, 243, 0.85)"
light_blue_background: "background-color: rgba(82, 170, 236, 0.85)"
cyan_background: "background-color: rgba(0, 188, 212, 0.85)"
teal_background: "background-color: rgba(0, 150, 136, 0.85)"
green_background: "background-color: rgba(76, 175, 80, 0.85)"
light_green_background: "background-color: rgba(139, 195, 74, 0.85)"
lime_background: "background-color: rgba(205, 220, 57, 0.85)"
yellow_background: "background-color: rgba(248, 188, 46, 0.85)"
amber_background: "background-color: rgba(255, 193, 7, 0.85)"
orange_background: "background-color: rgba(255, 152, 0, 0.85)"
deep_orange_background: "background-color: rgba(255, 87, 34, 0.85)"
brown_background: "background-color: rgba(121, 85, 72, 0.85)"
grey_background: "background-color: rgba(117, 117, 117, 0.85)"
light_grey_background: "background-color: rgba(238, 238, 238, 0.85)"
blue_grey_background: "background-color: rgba(96, 125, 139, 0.85)"

#Page and widget defaults
background_style: "background: transparent"
text_style: "color: $white"

#These are used for icons and indicators
style_inactive: "color: $white"
style_active: "color: $light_yellow; animation: rotate2 2s 1"
style_active_warn: "color: $red"
style_info: "color: $white"
style_title: "color: $white"
style_title2: "color: $white"

# Widget Default Definitions

scene_icon_on: fa-square
scene_icon_off: fa-square
scene_icon_style_active: $style_active
scene_icon_style_inactive: $style_inactive
scene_title_style: $style_title
scene_title2_style: $style_title2
scene_widget_style: $deep_purple_background
scene_state_text_style: "color: $white"

mode_icon_on: fa-arrows-alt
mode_icon_off: fa-arrows-alt
mode_icon_style_active: $style_active
mode_icon_style_inactive: $style_inactive
mode_title_style: $style_title
mode_title2_style: $style_title2
mode_widget_style: $purple_background
mode_state_text_style: "color: $white"

script_icon_on: fa-th-large
script_icon_off: fa-th-large
script_icon_style_active: $style_active
script_icon_style_inactive: $style_inactive
script_title_style: $style_title
script_title2_style: $style_title2
script_widget_style: $blue_grey_background
script_state_text_style: "color: $white"

binary_sensor_icon_on: fa-bullseye
binary_sensor_icon_off: fa-minus
binary_sensor_icon_style_active: $style_active
binary_sensor_icon_style_inactive: $style_inactive
binary_sensor_title_style: $style_title
binary_sensor_title2_style: $style_title2
binary_sensor_widget_style: $light_green_background
binary_sensor_state_text_style: "color: $white"

device_tracker_icon_on: fa-user
device_tracker_icon_off: fa-user
device_tracker_icon_style_active: $style_active
device_tracker_icon_style_inactive: $style_inactive
device_tracker_title_style: $style_title
device_tracker_title2_style: $style_title2
device_tracker_widget_style: $teal_background
device_tracker_state_text_style: "color: $light_grey"

input_boolean_icon_on: fa-sliders
input_boolean_icon_off: fa-sliders
input_boolean_icon_style_active: $style_active
input_boolean_icon_style_inactive: $style_inactive
input_boolean_title_style: $style_title
input_boolean_title2_style: $style_title2
input_boolean_widget_style: $deep_orange_background
input_boolean_state_text_style: "color: $light_grey"

switch_icon_on: fa-circle
switch_icon_off: fa-circle-thin
switch_icon_style_active: $style_active
switch_icon_style_inactive: $style_inactive
switch_title_style: $style_title
switch_title2_style: $style_title2
switch_widget_style: $light_blue_background
switch_state_text_style: "color: $white"

lock_icon_on: fa-unlock-alt
lock_icon_off: fa-lock
lock_icon_style_active: $style_active_warn
lock_icon_style_inactive: $style_inactive
lock_title_style: $style_title
lock_title2_style: $style_title2
lock_widget_style: $brown_background
lock_state_text_style: "color: $white"

cover_icon_on: fa-arrows-v
cover_icon_off: fa-arrows-v
cover_icon_style_active: $style_active_warn
cover_icon_style_inactive: $style_inactive
cover_title_style: $style_title
cover_title2_style: $style_title2
cover_widget_style: $blue_background
cover_state_text_style: "color: $light_grey"

clock_title_style: $style_title
clock_title2_style: $style_title2
clock_date_style: "color: $white"
clock_time_style: "color: $white"
clock_widget_style: $pink_background
# clock_date_style: "visibility: hidden; height: 0px"
# clock_time_style: "vertical-align: top; text-align: right; font-weight: 300; padding-right: 10px"
# clock_widget_style: "background-color: transparent; display: inline"

weather_main_style: "color: $white"
weather_unit_style: "color: $white"
weather_sub_style: "color: $white"
weather_widget_style: $yellow_background

caiyun_main_style: "color: $white"
caiyun_unit_style: "color: $white"
caiyun_sub_style: "color: $white"
caiyun_widget_style: $yellow_background

label_title_style: $style_title
label_title2_style: $style_title2
label_text_style: "color: $white"
label_widget_style: $lime_background

sensor_title_style: $style_title
sensor_title2_style: $style_title2
sensor_value_style: "color: $white; font-size: 250%"
sensor_text_style: "color: $light_grey; font-size: 100%"
sensor_unit_style: "color: $white; font-size: 100%"
sensor_widget_style: $cyan_background
sensor_state_text_style: $style_title

reload_icon_active: fa-spinner fa-spin

reload_icon_inactive: fa-refresh
reload_icon_active_style: "color: $white"
reload_icon_inactive_style: "color: $white"
reload_title_style: $style_title
reload_title2_style: $style_title2
#reload_widget_style: $background_style
reload_widget_style: $white0_background

navigate_icon_active: fa-spinner fa-spin
navigate_icon_inactive: fa-gear
navigate_icon_active_style: "color: $light_grey"
navigate_icon_inactive_style: "color: $light_grey"
navigate_title_style: $style_title
# navigate_title_style: "visibility: hidden; height: 0px"
navigate_title2_style: $style_title2
#navigate_widget_style: $background_style
navigate_widget_style: $white0_background


media_player_icon_play: fa-play
media_player_icon_pause: fa-pause
media_player_icon_stop: fa-stop
media_player_icon_up: fa-plus
media_player_icon_down: fa-minus
media_player_icon_next: fa-step-forward
media_player_icon_previous: fa-step-backward
media_player_title_style: $style_title
media_player_media_title_style: $style_title2
media_player_album_style: $style_title2
media_player_artist_style: $style_title2
media_player_icon_style_active: "color: $indigo"
media_player_icon_style_inactive: "color: $white"
media_player_state_text_style: "color: $light_grey"
media_player_units_style: "color: $light_grey"
media_player_level_style: "color: $light_grey"
media_player_level_up_style: "color: $white"
media_player_level_down_style: "color: $white"
media_player_widget_style: $pink_background
media_player_icon_style_previous: "color: $white"
media_player_icon_style_next: "color: $white"

light_icon_on: fa-circle
light_icon_off: fa-circle-thin
light_icon_up: fa-plus
light_icon_down: fa-minus
light_title_style: $style_title
light_title2_style: $style_title2
light_icon_style_active: $style_active
light_icon_style_inactive: $style_inactive
light_state_text_style: "color: $white"
light_level_style: "color: $light_grey"
light_unit_style:  "color: $light_grey"
light_level_up_style: "color: $white"
light_level_down_style: "color: $white"
light_widget_style: $red_background

input_slider_icon_up: fa-plus
input_slider_icon_down: fa-minus
input_slider_title_style: $style_title
input_slider_title2_style: $style_title2
input_slider_level_style: "color: $light_grey"
input_slider_unit_style: "color: $light_grey"
input_slider_level_up_style: "color: $white"
input_slider_level_down_style: "color: $white"
input_slider_widget_style: $indigo_background

climate_icon_up: fa-plus
climate_icon_down: fa-minus
climate_title_style: $style_title
climate_title2_style: $style_title2
climate_level_style: "color: $light_grey"
climate_unit_style: "color: $light_grey"
climate_level_up_style: "color: $white"
climate_level_down_style: "color: $white"
climate_widget_style: $indigo_background
climate_level2_style: "color: $light_grey"
climate_unit2_style: "color: $light_grey"

group_icon_on: fa-circle
group_icon_off: fa-circle-thin
# group_icon_on: fa-google-circles-communities
# group_icon_off: fa-google-circles-communities
group_icon_up: fa-plus
group_icon_down: fa-minus
group_title_style: $style_title
group_title2_style: $style_title2
group_icon_style_active: $style_active
group_icon_style_inactive: $style_inactive
group_state_text_style: "color: $light_grey"
group_level_style: "color: $light_grey"
group_level_up_style: "color: $white"
group_level_down_style: "color: $white"
group_widget_style: $grey_background
group_unit_style: "color: $light_grey"

iframe_title_style: "$style_title; background-color: rgba(0, 0, 0, 0.1)"
iframe_widget_style: $red_background

gauge_widget_style: $background_style
gauge_title_style: $style_title
gauge_title2_style: $style_title2
gauge_low_value_color: "$blue"
gauge_med_value_color: "$blue"
gauge_high_value_color: "$blue"
gauge_value_bgcolor: "$gray_medium"
gauge_widget_style: $brown_background
gauge_text_color: "$blue"

rss_title_style: "$style_title; color: $red"
rss_title2_style: "$style_title2; color: $red"
rss_text_style: "color: $blue"
rss_widget_style: $white_background

alarm_title_style: "color: $white"
alarm_widget_style: $background_style
alarm_title2_style: $style_title2
alarm_state_style: "color: $light_grey;font-size: 100%"
alarm_panel_state_style: "color: $light_grey"
alarm_panel_code_style: "color: $light_grey"
alarm_panel_background_style: $teal_background
alarm_panel_button_style: "background-color: $light_grey"

camera_widget_style: $cyan_background
camera_title_style: "$style_title; background-color: rgba(0, 0, 0, 0.1)"
